spring.application.name=lifestage
server.port=8080

eureka.instance.prefer-ip-address=true
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always


spring.security.oauth2.resourceserver.jwt.issuer-uri=https://lemur-9.cloud-iam.com/auth/realms/lifestage

# Makes hibernate create tables before seeding
spring.jpa.defer-datasource-initialization=true

# Makes hibernate create tables
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

# Seeding
spring.sql.init.mode=never



spring.profiles.default=dev
