spring.profiles.active=dev
eureka.client.service-url.defaultZone=http://localhost:9099/eureka

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/lifestage}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:lifestage}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:lifestage_pw}

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.security=DEBUG

