networks:
  app-network:
    driver: bridge
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lifestage -d lifestage"]
      interval: 5s
      retries: 5

  eureka-server:
    build:
      context: ./eureka
      dockerfile: Dockerfile
    ports:
      - "9099:9099"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9099/actuator/health"]
      interval: 10s
      retries: 5

  lifestage_backend:
    build: ./lifestage
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  cases_backend:
    build: ./cases
    ports:
      - "8081:8081"
    networks:
      - app-network
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
