spring.application.name=eureka

server.port=9099
eureka.instance.prefer-ip-address=true
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always