# Use a lightweight OpenJDK 21 base image
FROM eclipse-temurin:21-jdk
# Set the working directory inside the container
WORKDIR /app

# Copy the built JAR file into the container
COPY target/lifestage-0.0.1-SNAPSHOT.jar app.jar
# Expose the default Spring Boot port
EXPOSE 8080
# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]